language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=app manage.py test

after_success:
  - coveralls
